Nama : Syechan Ahmad Zidan

In [3]:
import numpy as np

In [22]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

# Hitunglah:

1. 2*A
2. 2+A
3. A+B
4. A-B
5. determinan A
6. invers dari B, simpan jadi matriks D
7. transpose D
8. nilai eigen dan vektor eigen dari A dan B

#### NOMOR 1

In [42]:
print ("nilai 2*A = \n", np.dot(2,A))
 


nilai 2*A = 
 [[ 2  4]
 [14 16]]


#### NOMOR 2

In [40]:
print("nilai 2+A = \n",2+A)

nilai 2+A = 
 [[ 3  4]
 [ 9 10]]


#### NOMOR 3

In [44]:
print("nilai A+B = \n", A+B)

nilai A+B = 
 [[ 4  7]
 [ 8 14]]


#### NOMOR 4

In [39]:
print("nilai A-B = \n" ,A-B)

nilai A-B = 
 [[-2 -3]
 [ 6  2]]


#### NOMOR 5

In [45]:
D = np.linalg.inv(B)

print("nilai D = \n",D)

nilai D = 
 [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]


#### NOMOR 6

In [46]:
print("nilai Det A = \n" ,np.linalg.det(A))

nilai Det A = 
 -6.0


#### NOMOR 7

In [47]:
print("nilai Transpose D = \n", D.transpose())

nilai Transpose D = 
 [[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]


#### NOMOR 8

In [48]:
print('nilai dan vektor eigen matriks A = \n', np.linalg.eig(A))


nilai dan vektor eigen matriks A = 
 (array([-0.62347538,  9.62347538]), array([[-0.77640358, -0.22592838],
       [ 0.63023605, -0.97414391]]))


#### Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)?

In [51]:
B*D

array([[ 1.38461538, -1.92307692],
       [-0.07692308,  1.38461538]])

In [53]:
print ("nilai B*D = \n", np.matmul(B,D))

nilai B*D = 
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


Perbedaan dari 2 perkalian diatas ialah, jika yang perkalian antar entry itu hanya dikalikan tiap variabel, jika perkalian antar matrix itu dikalian sesuai kaidak matrix yaitu baris dikali dengan kolom  